package com.jcp83.telegraph;

enum Status
{
    SERVER_IDLE,
    SERVER_STARTING,
    SERVER_STOPPING,
    SERVER_CONNECTOR_STARTING,
    SERVER_CONNECTOR_STOPPING,
    CLIENT_IDLE,
    CLIENT_STARTING,
    CLIENT_STOPPING,
    CLIENT_CONNECTOR_STARTING,
    CLIENT_CONNECTOR_STOPPING
}